### ISSUE TITLE
Hubspot::Form#submit requires the `:portal_id` parameter

### ISSUE THREAD

**Issue by hundredwatt** [adimichele/hubspot-ruby#17]
[`Hubspot::Form#submit`](https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/form.rb#L66)

The [`SUBMIT_DATA_PATH`](https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/form.rb#L12) constant includes a `:portal_id` parameter: `'/uploads/form/v2/:portal_id/:form_guid'`

However, the [`submit`](https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/form.rb#L66) instance method only passes the `:form_guid` in as a param: `Hubspot::Connection.post_json(FORM_PATH, params: { form_guid: @guid }, body: opts)`

So, when I attempted to use the `submit` method, an exception was raised:
```
Hubspot::ConfigurationError: 'portal_id' not configured
        from /Users/jason/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/hubspot-ruby-0.1.8/lib/hubspot/config.rb:24:in `block in ensure!'
        from /Users/jason/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/hubspot-ruby-0.1.8/lib/hubspot/config.rb:23:in `each'
        from /Users/jason/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/hubspot-ruby-0.1.8/lib/hubspot/config.rb:23:in `ensure!'
        from /Users/jason/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/hubspot-ruby-0.1.8/lib/hubspot/connection.rb:47:in `generate_url'
        from /Users/jason/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/hubspot-ruby-0.1.8/lib/hubspot/connection.rb:91:in `submit'
        from /Users/jason/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/hubspot-ruby-0.1.8/lib/hubspot/form.rb:66:in `submit'
```

Not sure what the appropriate resolution is, I can see 2 possiblities: 

1) include a `:portal_id` key in the `opts` hash 
2) Global configure the `portal_id`

**Comment by hundredwatt** [comment]
Nevermind, I figured out that I needed to configure `portal_id` in `Hubspot.configure` by reading this source code. This was the fix, change:

`Hubspot.configure(hapikey: ENV['HUBSPOT_API_KEY'])`

to

`Hubspot.configure(hapikey: ENV['HUBSPOT_API_KEY'])`
