### ISSUE TITLE
Contacts API test failure

### ISSUE THREAD

**Issue by adimichele** [adimichele/hubspot-ruby#3]
Discovered by @patrickdavey during pull request #2.

```
 1) Contacts API Live test finds a contact by utk
     Failure/Error: Hubspot::Contact.find_by_utk("f844d2217850188692f2610c717c2e9b").should be_present
       expected present? to return true, got false
     # ./spec/live/contacts_integration_spec.rb:30:in `block (2 levels) in <top (required)>'
     # ./spec/support/cassette_helper.rb:5:in `block in extended'
```

**Comment by cbisnett** [comment]
All tests pass on master so I'm going to close this. If this is still an issue, please reopen it. Thanks.
