### ISSUE TITLE
uninitialized constant Hubspot::Company

### ISSUE THREAD

**Issue by andrewcottage** [adimichele/hubspot-ruby#36]
I've installed the gem in my rails gemfile.

All of the other module subclasses are recognized and work as expected, but for some reason ::Company does not exist.

```
 Hubspot::Company
NameError: uninitialized constant Hubspot::Company
	from (irb):19
	from /home/andrew/.rvm/gems/ruby-2.3.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /home/andrew/.rvm/gems/ruby-2.3.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /home/andrew/.rvm/gems/ruby-2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/andrew/.rvm/gems/ruby-2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/andrew/.rvm/gems/ruby-2.3.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

My Code:
```
    company = Hubspot::Company.create!(name, {company_domain_name: realtor_url, phone_number: phone} )
```

**Comment by getlunchtray** [comment]
Having the same issue

**Comment by macano** [comment]
I have the same issue.

**Comment by andrewcottage** [comment]
I was able to fix this buy using 
```
gem "hubspot-ruby", github: 'adimichele/hubspot-ruby'
```

In my gemfile. 

I think the most recent gem version is out of date.
