### ISSUE TITLE
Requires ActiveSupport::Autoload

### ISSUE THREAD

**Issue by justinxreese** [adimichele/hubspot-ruby#38]
Was attempting to use this in a plain ruby project and this simple program

``` ruby
require 'dotenv'
require 'pry'
Dotenv.load

require 'hubspot-ruby'
```

Throws the following error:

```
/Users/justin/.gem/ruby/2.2.5/gems/activesupport-4.2.6/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>': uninitialized constant ActiveSupport::Autoload (NameError)
    from /Users/justin/.gem/ruby/2.2.5/gems/activesupport-4.2.6/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
    from /Users/justin/.gem/ruby/2.2.5/gems/activesupport-4.2.6/lib/active_support/number_helper.rb:1:in `<top (required)>'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/justin/.gem/ruby/2.2.5/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/justin/.gem/ruby/2.2.5/gems/activesupport-4.2.6/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /Users/justin/.gem/ruby/2.2.5/gems/activesupport-4.2.6/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
    from /Users/justin/.gem/ruby/2.2.5/gems/activesupport-4.2.6/lib/active_support/core_ext.rb:1:in `each'
    from /Users/justin/.gem/ruby/2.2.5/gems/activesupport-4.2.6/lib/active_support/core_ext.rb:1:in `<top (required)>'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /Users/justin/.gem/ruby/2.2.5/gems/hubspot-ruby-0.1.8/lib/hubspot-ruby.rb:1:in `<top (required)>'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from /Users/justin/.rubies/ruby-2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from app.rb:5:in `<main>'
```

**Comment by justinxreese** [comment]
I see ActiveSupport in the gemspec as a dependency, so I'm not sure why this happens. Maybe ActiveSupport::Autoload is not necessarily included

**Comment by justinxreese** [comment]
I'm able to solve this by requiring the following at the very beginning of my program:

```ruby
require 'active_support'
require 'active_support/deprecation'
```
