### ISSUE TITLE
Failure with Ruby 2.3.1

### ISSUE THREAD

**Issue by brandondrew** [adimichele/hubspot-ruby#49]
A script with just the line `require 'hubspot-ruby'` (everything else but the shebang line is commented out or after an `exit`) causes:

```
/Users/brandon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/deprecation/proxy_wrappers.rb:124:in `initialize': undefined method `instance' for ActiveSupport::Deprecation:Class (NoMethodError)
Did you mean?  instance_of?
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/load_error.rb:30:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext.rb:3:in `block in <top (required)>'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext.rb:2:in `each'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext.rb:2:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hubspot-ruby-0.1.8/lib/hubspot-ruby.rb:1:in `<top (required)>'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /Users/brandon/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from post.rb:5:in `<main>'
```

**Comment by brandondrew** [comment]
Ah: found the problem.  If you're not using this with Rails, and you're not using a Gemfile (because you were lazy and this was a quick script 😜 ) then you'll need to manually add 'active_support' as a dependency.
